FROM node:16.20.2

# Update package repository and install build-essential
RUN apt-get update && apt-get install -y build-essential netcat

# Install node-gyp globally
RUN npm install -g node-gyp

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json /app

# Install dependencies
RUN npm install

# Install Minio SDK
RUN npm install minio

# Copy application code
COPY . /app

# Expose port
EXPOSE 9010