import axios from "axios";
import { url } from "./config";
import {
  SET_FOLLOWUPS_OVERVIEW_COUNT,
  SET_FOLLOWUPS_OVERVIEW_CHART,
  SET_OVERVIEW_PORTFOLIO_COUNT,
  SET_REVENUE_BY_MEMBER_COUNT,
  SET_REVENUE_BY_MEMBER_CHART,
  SET_WORKSPACE_LEADS_ACTIVITY,
  SET_WORKSPACE_DEALS_ACTIVITY,
  SET_WORKSPACE_FOLLOWUP_ACTIVITY,
} from "./../types";
import Alert from "react-s-alert";

/*====================================================================
                        Communication Overview
======================================================================*/

export const communicationOverview = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/followups/comm-overview`,
      formData
    );
    if (data) {
      dispatch({
        type: SET_FOLLOWUPS_OVERVIEW_COUNT,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
                    Communication Overview Chart
======================================================================*/

export const communicationOverviewChart = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/followups/comm-overview-chart`,
      formData
    );
    if (data) {
      dispatch({
        type: SET_FOLLOWUPS_OVERVIEW_CHART,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
            Communication followups portfolio count
======================================================================*/

export const followupsPortfolioCount = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/followups/portfolio-count`,
      formData
    );
    if (data) {
      dispatch({
        type: SET_OVERVIEW_PORTFOLIO_COUNT,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
                 Revenue generated by member 
======================================================================*/

export const revenueGeneratedByMember = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/revenues/member-wise`,
      formData
    );
    if (data) {
      dispatch({ type: SET_REVENUE_BY_MEMBER_COUNT, payload: data });
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
            Revenue generated by member Chart 
======================================================================*/

export const revenueGeneratedByMemberChart = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/revenues/member-chart`,
      formData
    );
    if (data) {
      dispatch({ type: SET_REVENUE_BY_MEMBER_CHART, payload: data });
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
                    Create Workspace Activity
======================================================================*/

export const createWorkspaceActivity = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(`${url}/api/wacts`, formData);
    if (data) {
      console.log(data);
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
                    Get Workspace Activity
======================================================================*/

export const getWorkspaceActivity = () => async (dispatch) => {
  try {
    let { data, status } = await axios.get(
      `${url}/api/wacts?pageNo=1&pageSize=100`
    );
    if (data) {
      console.log(data);
    }
  } catch (err) {
    console.log(err);
  }
};

/*====================================================================
                     Search Workspace Activity
======================================================================*/

export const workspaceActivityForLeads = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/wacts/search`,
      formData
    );
    if (data) {
      // console.log(data);
      dispatch({
        type: SET_WORKSPACE_LEADS_ACTIVITY,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};

export const workspaceActivityForDeals = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/wacts/search`,
      formData
    );
    if (data) {
      dispatch({
        type: SET_WORKSPACE_DEALS_ACTIVITY,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};

export const workspaceActivityForFollowups = (formData) => async (dispatch) => {
  try {
    let { data, status } = await axios.post(
      `${url}/api/wacts/search`,
      formData
    );
    if (data) {
      dispatch({
        type: SET_WORKSPACE_FOLLOWUP_ACTIVITY,
        payload: data,
      });
    }
  } catch (err) {
    console.log(err);
  }
};
