const LeadStatus = Object.freeze({
  NEW_LEAD: 'NEW_LEAD',
  CONTACTED_LEADS: 'CONTACTED_LEADS',
  QUALIFIED_LEADS: 'QUALIFIED_LEADS',
  OPPORTUNITIES:'OPPORTUNITIES',
  CONVERTED: 'CONVERTED',
  ON_HOLD : 'ON_HOLD',
  ARCHIVE: 'ARCHIVE',
  DROPPED_LEAD:'DROPPED_LEAD'
})

module.exports = LeadStatus;