const NotificationType = Object.freeze({
  MEETING_CREATED: 'MEETING_CREATED',
  MEETING_UPDATED: 'MEETING_UPDATED',
  LEAD_CONVERTED_TO_CUSTOMER: 'LEAD_CONVERTED_TO_CUSTOMER',
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  LEAD_CLOSED:'LEAD_CLOSED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  PROPOSAL_RECEIVED: 'PROPOSAL_RECEIVED',
  QUOTATION_SENT: 'QUOTATION_SENT',
  QUOTATION_RECEIVED: 'QUOTATION_RECEIVED',
  FOLLOWUP_ADDED: 'FOLLOWUP_ADDED',
  FOLLOWUP_UPDATED: 'FOLLOWUP_UPDATED',
  DEAL_ADDED:'DEAL_CREATED',
  DEAL_UPDATED:'DEAL_UPDATED',
  DEAL_CLOSED:'DEAL_CLOSED',
  ORGANIZATION_MAKE_PAYMENT: 'ORGANIZATION_MAKE_PAYMENT',
  ORGANIZATION_DEACTIVATED: 'ORGANIZATION_DEACTIVATED',
  ORGANIZATION_ARCHIVE:'ORGANIZATION_ARCHIVE'

})

module.exports = NotificationType;