const PlanStatus = Object.freeze({
    TRIAL: 'TRIAL',
    FREE_PLAN:'FREE_PLAN',
    TRIAL_OVER:'TRIAL_OVER',
    PAID: 'PAID',
    CANCELLED: 'CANCELLED',
    TRIAL_ALMOST_OVER: 'TRIAL_ALMOST_OVER',
    TAO_PM_ATTACHED: 'TAO_PM_ATTACHED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    PAYMENT_VERIFIED: 'PAYMENT_VERIFIED'
  });
  
  module.exports = PlanStatus;