/**********************************************
 * @DESC - PROPOSAL
 **********************************************/
export const SET_PROPOSAL_INITIAL_DATA = "SET_PROPOSAL_INITIAL_DATA";
export const CLEAR_PROPOSAL_INITIAL_DATA = "CLEAR_PROPOSAL_INITIAL_DATA";

export const CREATE_PROPOSAL = "CREATE_PROPOSAL";
export const UPDATE_PROPOSAL = "UPDATE_PROPOSAL";
export const DELETE_PROPOSAL = "DELETE_PROPOSAL";
export const READ_ALL_PROPOSAL = "READ_ALL_PROPOSAL";
export const READ_PROPOSAL = "READ_PROPOSAL";
export const SET_PROPOSAL_OVERVIEW_COUNT = "SET_PROPOSAL_OVERVIEW_COUNT";

// autosave types
export const SET_SELECTED_TEMPLATES_BY_USER = "SET_SELECTED_TEMPLATES_BY_USER";
export const SET_AUTOSAVE_FALSE = "SET_AUTOSAVE_FALSE";
export const SET_AUTOSAVE = "SET_AUTOSAVE";
