module.exports = {
    SUCCESS: {code:"SUCCESS",message:"Success"},
    INTERNAL_SERVER_ERROR: {code:"INTERNAL_SERVER_ERROR",message:"Internal Server Error"},
    INVALID_INPUT : {code:"INVALID_INPUT",message:"Invalid input"}, 
    LOGIN_FAILED: {code:"LOGIN_FAILED",message:"Login Failed"},
    INVALID_ENVIRONMENT_USER: {code:"INVALID_ENVIRONMENT_USER",message:"Invalid Environment User"},
    EXCEED_EMAIL_LIMIT: {code: "EXCEED_EMAIL_LIMIT", message: "Maximum number of registration with same email address"},
    INVALID_MEDIA_TYPE: {code: "INVALID_MEDIA_TYPE", message: "Invalid Media Type"},
    INVALID_CONDITION: {code: "INVALID_CONDITION", message: "Invalid Condition"},
    USERNAME_EMAIL_REQUIRED: {code: "USERNAME_EMAIL_REQUIRED", message: "Username Email Required"},
    INVALID_MEDIA: {code: "INVALID_MEDIA", message: "Invalid Media"},
    INVALID_DATA: {code: "INVALID_DATA", message: "Invalid data"},
    NOT_FOUND: {code: "NOT_FOUND", message: "Resource not found"},
    INVALID_FILE: {code: "INVALID_FILE", message: "Invalid File"},  
    LIMIT_REACHED : {code: "LIMIT_REACHED", message: "Order limit reached"},
    LIMIT_EXCEEDED : {code: "LIMIT_EXCEEDED", message: "Limit exceeded"},
    ERROR_EMAIL : {code: "ERROR_EMAIL", message: "Email sending failed"},
    VALIDATION_FAILED: {code: "VALIDATION_FAILED", message: "Validation rule failed"},
    INVALID_TOKEN: {code: "INVALID_TOKEN", message: "Access Token is invalid"},
    USER_NOT_EXIST: {code: "USER_NOT_EXIST", message: "User does not exist"},
    USER_ALREADY_EXIST: {code: "USER_ALREADY_EXIST", message: "User already exist"},
    MISSING_QUERY_PARAM: {code: "MISSING_QUERY_PARAM", message: "Query param is not provided"},
    OPERATION_NOT_SUPPORTED: {code: "INTERNAL ORG UPDATION", message:"Cannot modify internal oraganization"},
    MISSING_ID: {code: "MISSING_ID", message: "Id is not provided"},
    LEAD_ALREADY_EXIST:{code: "LEAD_ALREADY_EXIST", message: "Lead already exist"},
    LEAD_NOT_EXIST: {code: "LEAD_NOT_EXIST", message: "Lead does not exist"},
    ACCESS_DENIED: {code: "ACCESS_DENIED", message: "Access Denied"},
    TASK_ALREADY_EXIST: {code:"TASK_ALREADY_EXIST", message: "Task already exist"},
    TASK_NOT_EXIST: {code:"TASK_NOT_EXIST", message:"Task not exist"},
    USER_NOT_ACTIVE: {code:"USER_NOT_ACTIVE", message:"User not active"},
    ORGANISATION_INACTIVE: {code:"ORGANISATION_INACTIVE", message:"Organisation is inactive"},
    ORGANIZATION_ALREADY_EXIST: {code:"ORGANIZATION_ALREADY_EXIST", message:"Organisation already exist"},
    ORGANIZATION_DOES_NOT_EXIST: {code:"ORGANIZATION_DOES_NOT_EXIST", message:"Organisation does not exist"},
    CUSTOMER_NOT_EXIST: {code: "CUSTOMER_NOT_EXIST", message: "Customer not exist"},
    CUSTOMER_ALREADY_EXIST: {code: "CUSTOMER_ALREADY_EXIST", message: "Customer already exist"},
    MEETING_NOT_EXIT:{code: "MEETING_NOT_EXIST", message: "Meeting doesn't exist"},
    CANNOT_APPROVE_LEAVE: {code: "CANNOT_APPROVE_LEAVE", message: "Cannot approve leave"},
    NOTIFICATION_NOT_EXIST: {code: "NOTIFICATION_NOT_EXIST", message: "Notification not exist"},
    INVALID_PLAN: {code: "INVALID_PLAN", message: "Plan not exist"} ,
    TARGET_ALREADY_EXIST: { code : "TARGET_ALREADY_EXIST", message:"Target for the given user or organisation already exists" },
    ORGANISATION_TARGET_NOT_EXIST: { code : "ORGANISATION_TARGET_NOT_EXIST", message:"Organisation Target must be set before creating employee target." },   
    INVALID_EMAIL_OPERATOR : {code: "INVALID_EMAIL_OPERATOR", message: "Email operator is required and should be google or microsoft"} ,
    ACCOUNT_DOES_NOT_EXIST: {code:"ACCOUNT_DOES_NOT_EXIST", message:"Account does not exist"},
    ACCOUNT_ALREADY_EXISTS: {code:"ACCOUNT_ALREADY_EXISTS", message:"Account already exists"},
    CONTACT_DOES_NOT_EXIST:{code:"CONTACT_DOES_NOT_EXIST", message:"contact does not exist"},
    CONTACT_ALREADY_EXISTS:{code:"CONTACT_ALREADY_EXISTS", message:"contact already exists"},
    CONTACT_EMAIL_ALREADY_EXISTS:{code:"CONTACT_EMAIL_ALREADY_EXISTS", message:"Email is already associated with an existing contact"},
    DEAL_DOES_NOT_EXIST: {code:"DEAL_DOES_NOT_EXIST", message:"Deal does not exist"},
    DEAL_ALREADY_EXISTS: {code: "DEAL_ALREADY_EXISTS", message:"Deal already exists"},
    PIPELINE_DOES_NOT_EXIST:{code:"PIPELINE_DOES_NOT_EXIST", message:"Pipeline does not exist"},
    PIPELINE_ALREADY_EXISTS:{code:"PIPELINE_ALREADY_EXISTS", message:"Pipeline already exists"},
    REVENUE_DOES_NOT_EXIST:{code:"REVENUE_DOES_NOT_EXIST", message:"Revenue does not exist"},
    REVENUE_ALREADY_EXISTS:{code:"REVENUE_ALREADY_EXISTS", message:"Revenue already exists"},
    LOG_DOES_NOT_EXIST:{code:"LOG_DOES_NOT_EXISTS", message:"Log does not exist"},
    LOG_ALREADY_EXISTS:{code:"LOG_ALREADY_EXISTS", message:"Log already exists"},
    ITARGET_DOES_NOT_EXIST:{code:"ITARGET_DOES_NOT_EXISTS", message:"Itarget does not exist"},
    ITARGET_ALREADY_EXISTS:{code:"ITARGET_ALREADY_EXISTS", message:"Itarget already exists"},
    OTARGET_DOES_NOT_EXIST:{code:"OTARGET_DOES_NOT_EXISTS", message:"Otarget does not exist"},
    OTARGET_ALREADY_EXISTS:{code:"OTARGET_ALREADY_EXISTS", message:"Otarget already exists"},
    ACHIEVEMENT_DOES_NOT_EXIST:{code:"ACHIEVEMENT_DOES_NOT_EXISTS", message:"Achievement does not exist"},
    ACHIEVEMENT_ALREADY_EXISTS:{code:"ACHIEVEMENT_ALREADY_EXISTS", message:"Achievement already exists"},
    FIELD_DOES_NOT_EXIST:{code:"FIELD_DOES_NOT_EXIST", message:"Field does not exist"},
    FIELD_ALREADY_EXISTS:{code:"FIELD_ALREADY_EXISTS", message:"Field already exists"},
    FVALUE_DOES_NOT_EXIST:{code:"FVALUE_DOES_NOT_EXISTS", message:"Fvalue does not exist"},
    FVALUE_ALREADY_EXISTS:{code:"FVALUE_ALREADY_EXISTS", message:"Fvalue already exists"},
    ITEM_ALREADY_EXISTS:{code:"ITEM_ALREADY_EXISTS", message:"Item with this name already exists"},
    ITEM_DOES_NOT_EXIST:{code:"ITEM_DOES_NOT_EXISTS", message:"Item does not exist"},
    SUBSCRIPTION_EXISTS:{code:"SUBSCRIPTION_EXISTS", message:"Subscription already exists, please update instead"},
    IDEALTARGET_ALDREADY_EXISTS:{code:"IDEALTARGET_ALREADY_EXISTS", message:"Idealtarget already exists"},
    IDEALTARGET_DOES_NOT_EXIST:{code:"IDEALTARGET_DOES_NOT_EXIST", message:"Idealtarget does not exists"},
    ODEALTARGET_ALREADY_EXISTS:{code:"ODEALTARGET_ALREADY_EXISTS", message:"Odealtarget already exists"},
    ODEALTARGET_DOES_NOT_EXIST:{code:"ODEALTARGET_DOES_NOT_EXIST", message:"Odealtarget does not exist"},
    DEALACHIEVE_ALREADY_EXISTS:{code:"DEALACHIEVE_ALREADY_EXISTS", message:"Dealachieve already exists"},
    CAMPAIGN_DOES_NOT_EXIST:{code:"CAMPAIGN_DOES_NOT_EXIST", message:"Campaign does not exist"},
    CAMPAIGN_NOT_SCHEDULED:{code:"CAMPAIGN_NOT_SCHEDULED", message:"Campaign has not been scheduled with the service so you cannot change status"},
    CAMPAIGN_DATA_NOT_COMPLETE:{code:"CAMPAIGN_DATA_NOT_COMPLETE", message:"Campaign data has not been filled entirely"},    
    ELIST_DOES_NOT_EXIST:{code:"ELIST_DOES_NOT_EXIST", message:"Elist does not exist"},
    REGDEMAIL_DOES_NOT_EXIST:{code:"REGDEMAIL_DOES_NOT_EXIST", message:"Regdemail does not exist"},
    VERIFIEDEMAIL_DOES_NOT_EXIST:{code:"VERIFIEDEMAIL_DOES_NOT_EXIST", message:"Verifiedemail does not exist"},
    LEADPIPELINE_ALREADY_EXISTS:{code:"LEADPIPELINE_ALREADY_EXISTS", message:"Leadpipeline already exists"},
    LEADPIPELINE_DOES_NOT_EXIST:{code:"LEADPIPELINE_DOES_NOT_EXIST", message:"Leadpipeline does not exist"},
    LEADSTAGE_ALREADY_EXISTS:{code:"LEADSTAGE_ALREADY_EXISTS", message:"Leadstage already exists"},
    LEADSTAGE_DOES_NOT_EXIST:{code:"LEADSTAGE_DOES_NOT_EXIST", message:"Leadstage does not exist"},
    INVALID_EMAIL_OR_PASSWORD:{code:"INVALID_EMAIL_OR_PASSWORD", message:"The password or email is invalid"},
    PASSWORD_DOES_NOT_MATCH:{code:"PASSWORD_DOES_NOT_MATCH", message:"The passwords don't match"},
    USER_WITH_EMAIL_DOES_NOT_EXIST:{code:"USER_WITH_EMAIL_DOES_NOT_EXIST", message:"User with this email does not exist"},
    REFERRAL_ALREADY_EXISTS:{code:"REFERRAL_ALREADY_EXISTS", message:"Referral already exists"},
    REFERRAL_DOES_NOT_EXIST:{code:"REFERRAL_DOES_NOT_EXIST", message:"Referral does not exist"},
    REFERRAL_ALREADY_USED_BY_USER:{code: "REFERRAL_ALREADY_USED_BY_USER", message:"A referral code has already been used by you in the past for signing up, you cannot use another referral code"},
    REFCODE_ALREADY_EXISTS:{code:"REFCODE_ALREADY_EXISTS", message:"RafCode already exists"},
    REFCODE_DOES_NOT_EXIST:{code:"REFCODE_DOES_NOT_EXIST", message:"RefCode does not exist"},
    REFERRAL_TO_ID_NEEDS_TO_BE_UNIQUE:{code:"REFERRAL_TO_ID_NEEDS_TO_BE_UNIQUE", message:"You have already created a referral code and cannot create another one"},
    REFERRAL_CODE_SEEMS_INCORRECT:{code:"REFERRAL_CODE_SEEMS_INCORRECT", message:"This referral doesn't seem correct, are you sure you've used the right one?"},
    USER_HAS_ALREADY_CREATED_REFERRAL_CODE:{code: "USER_HAS_ALREADY_CREATED_REFERRAL_CODE", message:"You have already created a referral code and cannot create another one"}
}
