export const SET_ERRORS = "SET_ERRORS";
export const GET_API_STATUS = "GET_API_STATUS";
export const SET_LOGIN = "SET_LOGIN";
export const LOGOUT_USER = "LOGOUT_USER";
export const VERIFY_EMPLOYEE = "VERIFY_EMPLOYEE";
export const GET_PLANS = "GET_PLANS";
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const SET_LOADER = "SET_LOADER";
export const CLEAR_LOADER = "CLEAR_LOADER";
export const GET_ALL_LEAD = "GET_ALL_LEAD";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_EMPLOYEE_OVERVIEW = "GET_EMPLOYEE_OVERVIEW";
export const GET_CUSTOMERS_OVERVIEW = "GET_CUSTOMERS_OVERVIEW";
export const GET_LEADS_OVERVIEW = "GET_LEADS_OVERVIEW";
export const GET_KANBAN_LEADS = "GET_KANBAN_LEADS";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const SET_ERROR_CODE = "SET_ERROR_CODE";

export const GET_CURRENT_LEAD_ADDED_DATA = "GET_CURRENT_LEAD_ADDED_DATA";
export const SET_EMPTY_STATUS = "SET_EMPTY_STATUS";
export const GET_STATUS_COUNT = "GET_STATUS_COUNT";
export const GET_LEADS_COUNT = "GET_LEADS_COUNT";
export const GET_LEAD_COUNT_BY_STATUS = "GET_LEAD_COUNT_BY_STATUS";
export const SET_ALL_TASKS = "SET_ALL_TASKS";
export const SET_FILTER_NAME = "SET_FILTER_NAME";
export const SET_APPROVAL_PENDING = "SET_APPROVAL_PENDING";
export const GET_KANBAN_STATUS_CHANGE = "GET_KANBAN_STATUS_CHANGE";
export const SET_SIGNUP_USER_INFO = "SET_SIGNUP_USER_INFO";
export const GET_ALL_PENDING_LEAVES = "GET_ALL_PENDING_LEAVES";
export const GET_ALL_FOLLOW_UPS = "GET_ALL_FOLLOW_UPS";
export const GET_ALL_MEETINGS = "GET_ALL_MEETINGS";
export const SET_ACTIVITY_EMAILS = "SET_ACTIVITY_EMAILS";
export const SET_ACTIVITY_DATA = "SET_ACTIVITY_DATA";
export const SET_ALL_HOLIDAYS = "SET_ALL_HOLIDAYS";
export const GET_ALL_APPROVED_LEAVES = "GET_ALL_APPROVED_LEAVES";
export const SET_EMPTY_ERRORS = "SET_EMPTY_ERRORS";
export const BEFORE_PAYMENT_DATA = "BEFORE_PAYMENT_DATA";
export const SET_ACTIVITY_NOTES = "SET_ACTIVITY_NOTES";
export const SET_APPROVAL_PENDING_LEAVES = "SET_APPROVAL_PENDING_LEAVES";
export const SET_EMAIL_TEMPLATES = "SET_EMAIL_TEMPLATES";
export const SET_ACTIVITY_ARCHIVE_EMAILS = "SET_ACTIVITY_ARCHIVE_EMAILS";
export const SET_CUSTOMER_EMAILS = "SET_CUSTOMER_EMAILS";
export const SET_CUSTOMER_ARCHIVE_EMAILS = "SET_CUSTOMER_ARCHIVE_EMAILS";
export const SET_EMPLOYEE_ACTIVITY = "SET_EMPLOYEE_ACTIVITY";
export const SET_EMPLOYEE_LEADS_OWN = "SET_EMPLOYEE_LEADS_OWN";
export const SET_LEAD_ACTIVITY_SUMMARY_INFO = "SET_LEAD_ACTIVITY_SUMMARY_INFO";
export const SET_LEADS_GENERATED_FROM_SOCIAL_MEDIA =
  "SET_LEADS_GENERATED_FROM_SOCIAL_MEDIA";
export const SET_TASK_COMPLETED_COUNT = "SET_TASK_COMPLETED_COUNT";
export const SET_SUPER_HOT_COUNT = "SET_SUPER_HOT_COUNT";
export const SET_COLD_COUNT = "SET_COLD_COUNT";
export const SET_HOT_COUNT = "SET_HOT_COUNT";
export const SET_WARM_COUNT = "SET_WARM_COUNT";
export const SET_ACTIVE_CUSTOMERS_COUNT = "SET_ACTIVE_CUSTOMERS_COUNT";
export const SET_TASK_LIST_COUNT = "SET_TASK_LIST_COUNT";
export const SET_TODAYS_MEET_AND_FOLLOWUP = "SET_TODAYS_MEET_AND_FOLLOWUP";
export const SET_TODAYS_MEET = "SET_TODAYS_MEET";
export const SET_CUSTOMER_STATUS_GRAPH = "SET_CUSTOMER_STATUS_GRAPH";
export const SET_EMAIL_GRAPH = "SET_EMAIL_GRAPH";
export const SET_SOCIAL_MEDIA_GRAPH = "SET_SOCIAL_MEDIA_GRAPH";
export const SET_LEADS_CLOSED_GRAPH = "SET_LEADS_CLOSED_GRAPH";
export const SET_LEADS_CLOSED_GRAPH_MONTHLY = "SET_LEADS_CLOSED_GRAPH_MONTHLY";
export const SET_LEADS_CLOSED_GRAPH_WEEKLY = "SET_LEADS_CLOSED_GRAPH_WEEKLY";
export const SET_LEADS_REVENU_GRAPH_YEARLY = "SET_LEADS_REVENU_GRAPH_YEARLY";
export const SET_LEADS_REVENU_GRAPH_MONTHLY = "SET_LEADS_REVENU_GRAPH_MONTHLY";
export const SET_LEADS_REVENU_GRAPH_WEEKLY = "SET_LEADS_REVENU_GRAPH_WEEKLY";
export const SET_YOUR_PREDICTION_GRAPH = "SET_YOUR_PREDICTION_GRAPH";
export const SET_USER_TARGET_GRAPH = "SET_USER_TARGET_GRAPH";
export const SET_PERFORMANCE_LEADERBOARD_CURRENT =
  "SET_PERFORMANCE_LEADERBOARD_CURRENT";
export const SET_PERFORMANCE_LEADERBOARD_PREVIOUS =
  "SET_PERFORMANCE_LEADERBOARD_PREVIOUS";
export const SET_UPCOMING_LEAVES = "SET_UPCOMING_LEAVES";
export const GET_ALL_ACTIVE_LEAD = "GET_ALL_ACTIVE_LEAD";
export const SET_ALL_LEADS_COUNT = "SET_ALL_LEADS_COUNT";
export const SET_LEADS_COUNT = "SET_LEADS_COUNT";
export const SET_ALL_QUOTATIONS = "SET_ALL_QUOTATIONS";
export const SET_QUOTATION_OVERVIEW = "SET_QUOTATION_OVERVIEW";
export const SET_EMAIL_IN_REDUCER = "SET_EMAIL_IN_REDUCER";
export const SET_CLICK_ON_QUOTATION = "SET_CLICK_ON_QUOTATION";
export const SET_EMPTY_QUOTATION = "SET_EMPTY_QUOTATION";
export const SET_EMPLOYEE_PERFORMANCE_GRAPH = "SET_EMPLOYEE_PERFORMANCE_GRAPH";
export const SET_ALL_HOLIDAYS_IN_YEAR = "SET_ALL_HOLIDAYS_IN_YEAR";
export const SET_LEADS_TIMELINE = "SET_LEADS_TIMELINE";
export const SET_EMPLOYEE_BLOCK_VIEW_POPUP_DATA =
  "SET_EMPLOYEE_BLOCK_VIEW_POPUP_DATA";
export const SET_LEAD_FILES = "SET_LEAD_FILES";
export const SET_ALL_CHAT_USERS = "SET_ALL_CHAT_USERS";
export const SET_ALL_CHATING_OF_USERS = "SET_ALL_CHATING_OF_USERS";
export const SET_DEFAULT_CHAT_USER_ID = "SET_DEFAULT_CHAT_USER_ID";
export const SET_DASHBOARD_NOTIFICATION = "SET_DASHBOARD_NOTIFICATION";
export const SET_ORGANIZATION_DETAILS = "SET_ORGANIZATION_DETAILS";
export const SET_ORGANIZATION_UPLOADED_IMAGE =
  "SET_ORGANIZATION_UPLOADED_IMAGE";
export const SET_KANBAN_VIEW = "SET_KANBAN_VIEW";
export const SET_SEARCH_IN_ALL_PAGE = "SET_SEARCH_IN_ALL_PAGE";
export const SET_PROPOSAL_OVERVIEW = "SET_PROPOSAL_OVERVIEW";
export const SET_PAGETITLE = "SET_PAGETITLE";
export const SET_BLOCK_VIEW = "SET_BLOCK_VIEW";
export const SET_BLOCK_VIEW_EMPLOYEE = "SET_BLOCK_VIEW_EMPLOYEE";
export const SET_DASHBOARD_CALENDER_WIDGET_CARD =
  "SET_DASHBOARD_CALENDER_WIDGET_CARD";
export const SET_DASHBOARD_CALENDER_WIDGET_MEET_FOLLOWUP =
  "SET_DASHBOARD_CALENDER_WIDGET_MEET_FOLLOWUP";
export const SET_CALENDER_FOLLOWUP_MEET_OF_THAT_DAY =
  "SET_CALENDER_FOLLOWUP_MEET_OF_THAT_DAY";
export const SET_REPORTS_LEADS_DROP = "SET_REPORTS_LEADS_DROP";
export const SET_LEADS_LEVELS_GRAPH_DATA = "SET_LEADS_LEVELS_GRAPH_DATA";
export const SET_DASHBOARD_MONTH_STATUS_COUNT =
  "SET_DASHBOARD_MONTH_STATUS_COUNT";
export const SET_LEADS_SOURCE_BY_REVENUE = "SET_LEADS_SOURCE_BY_REVENUE";
export const SET_DEALS_IN_PIPELINE = "SET_DEALS_IN_PIPELINE";
export const SET_TODAYS_TASKS = "SET_TODAYS_TASKS";
export const SET_MONTHLY_TARGET_BY_DOLLER = "SET_MONTHLY_TARGET_BY_DOLLER";
export const SET_MONTHLY_TARGET_BY_LEAD = "SET_MONTHLY_TARGET_BY_LEAD";
export const SET_OWNER_WISE_LEADS = "SET_OWNER_WISE_LEADS";
export const SET_ORGANISATION_TARGET = "SET_ORGANISATION_TARGET";
export const GET_ALL_EMPLOYEES_TARGET = "GET_ALL_EMPLOYEES_TARGET";
export const SET_SIGNLE_EMPLOYEE_TARGET = "SET_SIGNLE_EMPLOYEE_TARGET";
export const SET_MONTHLY_AND_QUATERLY_REVENUE =
  "SET_MONTHLY_AND_QUATERLY_REVENUE";
export const SET_REVENUE_FORCAST_GRAPH_DATA = "SET_REVENUE_FORCAST_GRAPH_DATA";
export const SET_EXPECTED_VS_AQUIRED_REVENUE =
  "SET_EXPECTED_VS_AQUIRED_REVENUE";
export const SET_BILLING_HISTORY = "SET_BILLING_HISTORY";
export const SET_CALENDER_FOLLOWUP_SELECTED_DAY =
  "SET_CALENDER_FOLLOWUP_SELECTED_DAY";
export const SET_OVERVIEW_FILTERNAME = "SET_OVERVIEW_FILTERNAME";
export const SET_CONFETTI_ANIMATION = "SET_CONFETTI_ANIMATION";
export const SET_EDIT_OR_VIEW = "SET_EDIT_OR_VIEW";
export const SET_SINGLE_EMPLOYEE_DATA = "SET_SINGLE_EMPLOYEE_DATA";
export const SET_LEAD_ACTIVITY_LOG = "SET_LEAD_ACTIVITY_LOG";
export const SET_ACCOUNT_WITH_MAX_REVENUE = "SET_ACCOUNT_WITH_MAX_REVENUE";
export const SET_TOTAL_REVENUE_GENERATED_MONTHWISE =
  "SET_TOTAL_REVENUE_GENERATED_MONTHWISE";
export const SET_REVENUE_GENERATED_FROM_RECURRING_DEALS =
  "SET_REVENUE_GENERATED_FROM_RECURRING_DEALS";
export const SET_BIGGEST_DEAL_REVENUE = "SET_BIGGEST_DEAL_REVENUE";
export const SET_FUTURE_REVENUE_PROJECTION = "SET_FUTURE_REVENUE_PROJECTION";
export const SET_FUTURE_REVENUE_PREDICTION = "SET_FUTURE_REVENUE_PREDICTION";
export const SET_DEALS_AND_LEADS_OF_ACCOUNT_CHART =
  "SET_DEALS_AND_LEADS_OF_ACCOUNT_CHART";
export const GET_CLOSED_DEAL_BY_MONTH_CHART = "GET_CLOSED_DEAL_BY_MONTH_CHART";
export const SET_TOTAL_REVENUE_GENERATED_BY_ACCOUNT =
  "SET_TOTAL_REVENUE_GENERATED_BY_ACCOUNT";
export const SET_ORGANIZATION_TARGET_VS_DOLLER_CHART =
  "SET_ORGANIZATION_TARGET_VS_DOLLER_CHART";
export const SET_ORGANIZATION_TARGET_VS_ACTUAL_LEADS_CHART =
  "SET_ORGANIZATION_TARGET_VS_ACTUAL_LEADS_CHART";
export const SET_ORGANIZATION_TARGET_EFFICIENCY =
  "SET_ORGANIZATION_TARGET_EFFICIENCY";
export const SET_USER_TARGET_VS_DOLLER_CHART =
  "SET_USER_TARGET_VS_DOLLER_CHART";
export const SET_USER_TARGET_VS_LEADS_CHART = "SET_USER_TARGET_VS_LEADS_CHART";
export const SET_USER_TARGET_EFFICIENCY = "SET_USER_TARGET_EFFICIENCY";
export const SET_ORGANIZATION_TARGET_TABLE = "SET_ORGANIZATION_TARGET_TABLE";
export const SET_USER_TARGET_TABLE = "SET_USER_TARGET_TABLE";
export const SET_ALL_USERS_ROLES = "SET_ALL_USERS_ROLES";
export const SET_ALL_CUSTOM_FIELDS = "SET_ALL_CUSTOM_FIELDS";
export const SET_LEADS_ALL_CUSTOME_FIELDS = "SET_LEADS_ALL_CUSTOME_FIELDS";
export const SET_ACCOUNT_ALL_CUSTOME_FIELDS = "SET_ACCOUNT_ALL_CUSTOME_FIELDS";
export const SET_CONTACT_ALL_CUSTOME_FIELDS = "SET_CONTACT_ALL_CUSTOME_FIELDS";
export const GET_FIELDS_VALUE_BY_ENTITY = "GET_FIELDS_VALUE_BY_ENTITY";
export const SET_DEAL_ALL_CUSTOME_FIELDS = "SET_DEAL_ALL_CUSTOME_FIELDS";
export const SET_SINGLE_LEAD_CLOSURE_PROBABLITY =
  "SET_SINGLE_LEAD_CLOSURE_PROBABLITY";

/*=========================================
     command center deal target
===========================================*/

//org target
export const SET_ORGANISATION_DEAL_TARGET = "SET_ORGANISATION_DEAL_TARGET";
export const SET_ORGANIZATION_TARGET_VS_ACTUAL_DEALS_CHART =
  "SET_ORGANIZATION_TARGET_VS_ACTUAL_DEALS_CHART";
export const SET_ORGANIZATION_DEAL_TARGET_VS_DOLLER_CHART =
  "SET_ORGANIZATION_DEAL_TARGET_VS_DOLLER_CHART";
export const SET_ORGANIZATION_DEAL_TARGET_EFFICIENCY =
  "SET_ORGANIZATION_DEAL_TARGET_EFFICIENCY";
export const SET_ORGANIZATION_DEAL_TARGET_TABLE =
  "SET_ORGANIZATION_DEAL_TARGET_TABLE";
//team target
export const SET_SIGNLE_DEAL_EMPLOYEE_TARGET =
  "SET_SIGNLE_DEAL_EMPLOYEE_TARGET";
export const SET_USER_DEAL_TARGET_VS_DOLLER_CHART =
  "SET_USER_DEAL_TARGET_VS_DOLLER_CHART";
export const SET_USER_DEAL_TARGET_EFFICIENCY =
  "SET_USER_DEAL_TARGET_EFFICIENCY";
export const SET_USER_TARGET_VS_DEAL_CHART = "SET_USER_TARGET_VS_DEAL_CHART";
export const SET_USER_DEAL_TARGET_TABLE = "SET_USER_DEAL_TARGET_TABLE";

// Lead active team target
export const SET_TARGET_USER_FILTER_ACTIVE_MEMBER =
  "SET_TARGET_USER_FILTER_ACTIVE_MEMBER";

/*==========================================
          Deals In PIPELINE  types
============================================*/
export const SET_ALL_DEALS_IN_PIPELINE = "SET_ALL_DEALS_IN_PIPELINE";
export const SET_STACK_OF_PERTICULAR_PIPELINE =
  "SET_STACK_OF_PERTICULAR_PIPELINE";
export const SET_CLOSED_STACK_OF_PERTICULAR_PIPELINE =
  "SET_CLOSED_STACK_OF_PERTICULAR_PIPELINE";
export const SET_DEALS_OVERVIEW = "SET_DEALS_OVERVIEW";

/*==========================================
              Account Types
============================================*/
export const SET_ALL_ACCOUNTS = "SET_ALL_ACCOUNTS";
export const SET_SINGLE_ACCOUNT_DATA = "SET_SINGLE_ACCOUNT_DATA";
export const SET_DEALS_OF_ACCOUNT = "SET_DEALS_OF_ACCOUNT";
export const SET_LEADS_OF_ACCOUNT = "SET_LEADS_OF_ACCOUNT";
export const SET_ACCOUNTS_OVERVIEW = "SET_ACCOUNTS_OVERVIEW";
export const SET_REVENUE_OVERVIEW = "SET_REVENUE_OVERVIEW";
export const SET_DEALS_AND_THEIR_REVENUE = "SET_DEALS_AND_THEIR_REVENUE";
export const SET_REVENUE_FORCAST_GRAPH = "SET_REVENUE_FORCAST_GRAPH";
export const SET_ACCOUNT_ACTIVITY = "SET_ACCOUNT_ACTIVITY";
export const SET_ACCOUNT_ACCUMULATED_GRAPH = "SET_ACCOUNT_ACCUMULATED_GRAPH";
export const SET_ACCOUNTS_WITH_DEALS_CHART = "SET_ACCOUNTS_WITH_DEALS_CHART";
export const SET_ACCOUNT_NOTES = "SET_ACCOUNT_NOTES";
export const GET_NOTE_DATA = "GET_NOTE_DATA";
/*==========================================
              Contact Types
============================================*/

export const SET_ALL_CONTACT = "SET_ALL_CONTACT";
export const SET_SELECTED_CONTACTS = "SET_SELECTED_CONTACTS";
export const SET_ASSIGNED_MEMBER = "SET_ASSIGNED_MEMBER";
export const SET_ASSIGNED_ACCOUNT = "SET_ASSIGNED_ACCOUNT";
export const SET_CONTACT_VALIDATION_ERROR = "SET_CONTACT_VALIDATION_ERROR";

/*==========================================
              Deals Types
============================================*/

export const SET_SINGLE_DEAL_DATA = "SET_SINGLE_DEAL_DATA";

/*==========================================
          Super Admin Types
  ===========================================*/
export const SET_SUPERADMIN_ORGANIZATIONS = "SET_SUPERADMIN_ORGANIZATIONS";
export const SET_PERTICULAR_WORKSPACE_INFO = "SET_PERTICULAR_WORKSPACE_INFO";
export const SET_ORGANIZATION_OVERVIEW = "SET_ORGANIZATION_OVERVIEW";
export const GET_SINGLE_ORGANIZATION_OVERVIEW =
  "GET_SINGLE_ORGANIZATION_OVERVIEW";
export const GET_SUPERADMIN_FILTERNAME = "GET_SUPERADMIN_FILTERNAME";
export const SET_MANUAL_RETRY_COUNT = "SET_MANUAL_RETRY_COUNT";

/*==========================================
              Walkthrough
============================================*/

export const SET_WALKTHROUGH_PAGE = "SET_WALKTHROUGH_PAGE";

/*==========================================
              Payment Types
============================================*/
export const SET_FUTURE_PAYMENT_INVOICE = "SET_FUTURE_PAYMENT_INVOICE";
export const SET_PAYMENT_HISTORY = "SET_PAYMENT_HISTORY";
export const SET_PAYMENT_SAVED_CARDS = "SET_PAYMENT_SAVED_CARDS";
export const SET_CUSTOMER_ACCOUTN_BALENCE = "SET_CUSTOMER_ACCOUTN_BALENCE";

/*=============================================
        PROPSALS BY CRAFTJS TYPES
===============================================*/
export const SET_PROPOSAL_BY_CRAFT_OVERVIEW_COUNT =
  "SET_PROPOSAL_BY_CRAFT_OVERVIEW_COUNT";
export const GET_ALL_PROPOSALS_BY_CRAFT_LIST =
  "GET_ALL_PROPOSALS_BY_CRAFT_LIST";
export const SET_ALL_CRAFTJS_HTML = "SET_ALL_CRAFTJS_HTML";
export const SET_EDITOR_ENABLE_OR_NOT = "SET_EDITOR_ENABLE_OR_NOT";

/*=============================================
          Product and services types
===============================================*/
export const SET_PRODUCT_AND_SERVICES = "SET_PRODUCT_AND_SERVICES";

/*=============================================
                 Vault Types
===============================================*/

export const SET_ALL_FOLDERS = "SET_ALL_FOLDERS";
export const SET_FILES_OF_FOLDER = "SET_FILES_OF_FOLDER";

/*=============================================
          Workspace activity log types
===============================================*/
export const SET_FOLLOWUPS_OVERVIEW_COUNT = "SET_FOLLOWUPS_OVERVIEW_COUNT";
export const SET_FOLLOWUPS_OVERVIEW_CHART = "SET_FOLLOWUPS_OVERVIEW_CHART";
export const SET_OVERVIEW_PORTFOLIO_COUNT = "SET_OVERVIEW_PORTFOLIO_COUNT";
export const SET_REVENUE_BY_MEMBER_COUNT = "SET_REVENUE_BY_MEMBER_COUNT";
export const SET_REVENUE_BY_MEMBER_CHART = "SET_REVENUE_BY_MEMBER_CHART";
export const SET_WORKSPACE_LEADS_ACTIVITY = "SET_WORKSPACE_LEADS_ACTIVITY";
export const SET_WORKSPACE_DEALS_ACTIVITY = "SET_WORKSPACE_DEALS_ACTIVITY";
export const SET_WORKSPACE_FOLLOWUP_ACTIVITY =
  "SET_WORKSPACE_FOLLOWUP_ACTIVITY";

/*==============================================
                 Microsoft Types
===============================================*/

export const SET_ALL_MICROSOFT_FOLDERS = "SET_ALL_MICROSOFT_FOLDERS";
export const SET_FOLDERS_MESSEGES = "SET_FOLDERS_MESSEGES";
export const SET_ALL_MICROSOFT_CONTACTS = "SET_ALL_MICROSOFT_CONTACTS";
export const SET_ALL_MICROSOFT_EVENTS = "SET_ALL_MICROSOFT_EVENTS";
export const SET_MICROSOFT_SINGLE_MESSAGE = "SET_MICROSOFT_SINGLE_MESSAGE";
/*===============================================
                Calender Types
=================================================*/
export const SET_ALL_HOLIDAYS_IN_MONTH = "SET_ALL_HOLIDAYS_IN_MONTH";
export const SET_ALL_PENDING_AND_APPROVED_LEAVES =
  "SET_ALL_PENDING_AND_APPROVED_LEAVES";
export const SET_CALENDER_DATA_OF_DAY = "SET_CALENDER_DATA_OF_DAY";
export const SET_TODAYS_SCHEDULE = "SET_TODAYS_SCHEDULE";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

/*===============================================
                    Leads Notes
=================================================*/
export const SET_SELECTED_NOTE = "SET_SELECTED_NOTE";

/*==================================================
               Sequences types
====================================================*/
export const SET_CONTACTS_WITH_EMAILS = "SET_CONTACTS_WITH_EMAILS";
export const SET_ELIST_CONTACTS = "SET_ELIST_CONTACTS";
export const SET_ALL_ELISTS = "SET_ALL_ELISTS";
export const SET_SINGLE_ELIST_DATA = "SET_SINGLE_ELIST_DATA";
export const SET_ALL_REGITERED_AND_NOT_MAILS =
  "SET_ALL_REGITERED_AND_NOT_MAILS";
export const SET_ALL_CAMPAIGNS = "SET_ALL_CAMPAIGNS";
export const SET_SINGLE_CAMPAIGN_ALL_DATA = "SET_SINGLE_CAMPAIGN_ALL_DATA";
export const SET_CAMPAIGN_EMAIL_TEMPLATES = "SET_CAMPAIGN_EMAIL_TEMPLATES";
export const SET_BLOCK_DETAIL_TEMPLATE = "SET_BLOCK_DETAIL_TEMPLATE";

/*===============================================
                ADMIN SETTING TYPES
=================================================*/
export const GET_INVITE_LINK_USERS = "GET_INVITE_LINK_USERS";

/*===============================================
              LEADS TYPES
=================================================*/

export const SET_KANBAN_SEARCH = "SET_KANBAN_SEARCH";

/*===============================================
              LEADS PIPELINE TYPES
=================================================*/

export const SET_ALL_LEADS_PIPELINE = "SET_ALL_LEADS_PIPELINE";
export const SET_LEADS_PIPELINE_STAGES = "SET_LEADS_PIPELINE_STAGES";
export const SET_ALL_LEADS_OF_PIPELINE = "SET_ALL_LEADS_OF_PIPELINE";
export const SET_PIPELINE_FUNNEL_VIEW = "SET_PIPELINE_FUNNEL_VIEW";
export const SET_ALL_LEADS_COUNT_OF_PIPELINE =
  "SET_ALL_LEADS_COUNT_OF_PIPELINE";
export const SET_ALL_PIPELINE_LEADS = "SET_ALL_PIPELINE_LEADS";
export const SET_OVERALL_PIPE_LEADS = "SET_OVERALL_PIPE_LEADS";
export const SET_ALL_PIPELINE_LEADS_COUNT = "SET_ALL_PIPELINE_LEADS_COUNT";

/*===============================================
             REFERRAL TYPES
=================================================*/

export const SET_GENERATED_REFERRAL_CODE = "SET_GENERATED_REFERRAL_CODE";
export const SET_ALL_REFERRALS_DATA = "SET_ALL_REFERRALS_DATA";
export const SET_REFERRAL_DATA_OF_LOGEDIN_USER =
  "SET_REFERRAL_DATA_OF_LOGEDIN_USER";
