FROM node:15.5.1-alpine

#RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
#RUN npm install --quiet node-gyp -g

COPY package.json ./

RUN npm install

# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

CMD [ "npm", "start" ]